#include "common.h" // retro delta: fork-owned RIR kernels
// Generated by rir-gen — DO NOT EDIT MANUALLY.
// Every production RIR kernel body for Metal, concatenated
// (docs/INT_RIR_V3.md §R0). `ggml-metal.metal` includes this file in one
// line; there is no marker-delimited copy to keep in step any more.
//
// This is an include fragment, not a translation unit: it opens no
// namespace and includes no header. The standalone per-variant sources
// under generated/rir/<kernel>/ remain what the compile test compiles.

// ---- l2_norm_back ----
struct rir_l2_norm_back_params {
    float eps;
    uint n_row;
    uint n_plane;
    uint n_batch;
    uint n_col;
    uint dz_nb0;
    uint dz_nb1;
    uint dz_nb2;
    uint dz_nb3;
    uint x_nb0;
    uint x_nb1;
    uint x_nb2;
    uint x_nb3;
    uint dx_nb0;
    uint dx_nb1;
    uint dx_nb2;
    uint dx_nb3;
};

kernel void rir_l2_norm_back(
    device const uchar* dz [[buffer(0)]],
    device const uchar* x [[buffer(1)]],
    device uchar* dx [[buffer(2)]],
    constant rir_l2_norm_back_params& pc [[buffer(3)]],
    uint3 group_id [[threadgroup_position_in_grid]],
    uint3 global_id [[thread_position_in_grid]],
    uint simd_lane_id [[thread_index_in_simdgroup]])
{
    const uint row_v0 = group_id.x;
    if (row_v0 >= pc.n_row) {
        return;
    }
    const uint plane_v1 = group_id.y;
    if (plane_v1 >= pc.n_plane) {
        return;
    }
    const uint batch_v2 = group_id.z;
    if (batch_v2 >= pc.n_batch) {
        return;
    }
    const uint lane_v3 = simd_lane_id;
    float acc9_v4 = 0.0f;
    float acc10_v5 = 0.0f;
    const uint base_v25 = row_v0 * pc.x_nb1 + plane_v1 * pc.x_nb2 + batch_v2 * pc.x_nb3;
    const uint base_v26 = row_v0 * pc.dz_nb1 + plane_v1 * pc.dz_nb2 + batch_v2 * pc.dz_nb3;
    for (uint col_v6 = lane_v3; col_v6 < pc.n_col; col_v6 += 32u) {
        const float t_v7 = *(device const float *)(x + (col_v6 * pc.x_nb0 + base_v25));
        const float t_v8 = t_v7 * t_v7;
        acc9_v4 += t_v8;
        const float t_v9 = *(device const float *)(dz + (col_v6 * pc.dz_nb0 + base_v26));
        const float t_v10 = t_v7 * t_v9;
        acc10_v5 += t_v10;
    }
    const float red9_v11 = simd_sum(acc9_v4);
    const float red10_v12 = simd_sum(acc10_v5);
    const float t_v14 = sqrt(red9_v11);
    const float p_v15 = pc.eps;
    const bool b_v16 = t_v14 > p_v15;
    const uint base_v27 = row_v0 * pc.dz_nb1 + plane_v1 * pc.dz_nb2 + batch_v2 * pc.dz_nb3;
    const uint base_v28 = row_v0 * pc.x_nb1 + plane_v1 * pc.x_nb2 + batch_v2 * pc.x_nb3;
    const float t_v19 = red10_v12 / red9_v11;
    const uint base_v29 = row_v0 * pc.dx_nb1 + plane_v1 * pc.dx_nb2 + batch_v2 * pc.dx_nb3;
    for (uint col_v13 = lane_v3; col_v13 < pc.n_col; col_v13 += 32u) {
        const float t_v17 = *(device const float *)(dz + (col_v13 * pc.dz_nb0 + base_v27));
        const float t_v18 = *(device const float *)(x + (col_v13 * pc.x_nb0 + base_v28));
        const float t_v20 = t_v18 * t_v19;
        const float t_v21 = t_v17 - t_v20;
        const float t_v22 = t_v21 / t_v14;
        const float t_v23 = t_v17 / p_v15;
        const float t_v24 = b_v16 ? t_v22 : t_v23;
        *(device float *)(dx + (col_v13 * pc.dx_nb0 + base_v29)) = t_v24;
    }
}

// ---- cumsum ----
struct rir_cumsum_params {
    uint n_row;
    uint n_plane;
    uint n_batch;
    uint n_col;
    uint x_nb0;
    uint x_nb1;
    uint x_nb2;
    uint x_nb3;
    uint y_nb0;
    uint y_nb1;
    uint y_nb2;
    uint y_nb3;
};

kernel void rir_cumsum(
    device const uchar* x [[buffer(0)]],
    device uchar* y [[buffer(1)]],
    constant rir_cumsum_params& pc [[buffer(2)]],
    uint3 group_id [[threadgroup_position_in_grid]],
    uint3 global_id [[thread_position_in_grid]],
    uint simd_lane_id [[thread_index_in_simdgroup]])
{
    const uint row_v0 = global_id.x;
    if (row_v0 >= pc.n_row) {
        return;
    }
    const uint plane_v1 = global_id.y;
    if (plane_v1 >= pc.n_plane) {
        return;
    }
    const uint batch_v2 = global_id.z;
    if (batch_v2 >= pc.n_batch) {
        return;
    }
    float scan5_v3 = 0.0f;
    const uint base_v7 = row_v0 * pc.x_nb1 + plane_v1 * pc.x_nb2 + batch_v2 * pc.x_nb3;
    const uint base_v8 = row_v0 * pc.y_nb1 + plane_v1 * pc.y_nb2 + batch_v2 * pc.y_nb3;
    for (uint col_v4 = 0u; col_v4 < pc.n_col; ++col_v4) {
        const float t_v5 = *(device const float *)(x + (col_v4 * pc.x_nb0 + base_v7));
        scan5_v3 += t_v5;
        const float s5_v6 = scan5_v3;
        *(device float *)(y + (col_v4 * pc.y_nb0 + base_v8)) = s5_v6;
    }
}

// ---- cumsum_blocked ----
struct rir_cumsum_blocked_params {
    uint n_row;
    uint n_plane;
    uint n_batch;
    uint n_col;
    uint x_nb0;
    uint x_nb1;
    uint x_nb2;
    uint x_nb3;
    uint y_nb0;
    uint y_nb1;
    uint y_nb2;
    uint y_nb3;
};

kernel void rir_cumsum_blocked(
    device const uchar* x [[buffer(0)]],
    device uchar* y [[buffer(1)]],
    constant rir_cumsum_blocked_params& pc [[buffer(2)]],
    uint3 group_id [[threadgroup_position_in_grid]],
    uint3 global_id [[thread_position_in_grid]],
    uint simd_lane_id [[thread_index_in_simdgroup]])
{
    const uint row_v0 = group_id.x;
    if (row_v0 >= pc.n_row) {
        return;
    }
    const uint plane_v1 = group_id.y;
    if (plane_v1 >= pc.n_plane) {
        return;
    }
    const uint batch_v2 = group_id.z;
    if (batch_v2 >= pc.n_batch) {
        return;
    }
    const uint lane_v3 = simd_lane_id;
    float part5_v4 = 0.0f;
    const uint base_v12 = row_v0 * pc.x_nb1 + plane_v1 * pc.x_nb2 + batch_v2 * pc.x_nb3;
    const uint chunk_col_v5 = (pc.n_col + 32u - 1u) / 32u;
    const uint beg_col_v5 = min(lane_v3 * chunk_col_v5, pc.n_col);
    const uint end_col_v5 = min((lane_v3 + 1u) * chunk_col_v5, pc.n_col);
    for (uint col_v5 = beg_col_v5; col_v5 < end_col_v5; ++col_v5) {
        const float t_v6 = *(device const float *)(x + (col_v5 * pc.x_nb0 + base_v12));
        part5_v4 += t_v6;
    }
    const float off5_v7 = simd_prefix_exclusive_sum(part5_v4);
    float scan5_v9 = 0.0f;
    scan5_v9 += off5_v7;
    const uint base_v13 = row_v0 * pc.x_nb1 + plane_v1 * pc.x_nb2 + batch_v2 * pc.x_nb3;
    const uint base_v14 = row_v0 * pc.y_nb1 + plane_v1 * pc.y_nb2 + batch_v2 * pc.y_nb3;
    const uint chunk_col_v8 = (pc.n_col + 32u - 1u) / 32u;
    const uint beg_col_v8 = min(lane_v3 * chunk_col_v8, pc.n_col);
    const uint end_col_v8 = min((lane_v3 + 1u) * chunk_col_v8, pc.n_col);
    for (uint col_v8 = beg_col_v8; col_v8 < end_col_v8; ++col_v8) {
        const float t_v10 = *(device const float *)(x + (col_v8 * pc.x_nb0 + base_v13));
        scan5_v9 += t_v10;
        const float s5_v11 = scan5_v9;
        *(device float *)(y + (col_v8 * pc.y_nb0 + base_v14)) = s5_v11;
    }
}

// ---- cumsum_shared ----
struct rir_cumsum_shared_params {
    uint n_row;
    uint n_plane;
    uint n_batch;
    uint n_col;
    uint x_nb0;
    uint x_nb1;
    uint x_nb2;
    uint x_nb3;
    uint y_nb0;
    uint y_nb1;
    uint y_nb2;
    uint y_nb3;
};

kernel void rir_cumsum_shared(
    device const uchar* x [[buffer(0)]],
    device uchar* y [[buffer(1)]],
    constant rir_cumsum_shared_params& pc [[buffer(2)]],
    uint3 group_id [[threadgroup_position_in_grid]],
    uint3 global_id [[thread_position_in_grid]],
    uint threadgroup_lane_id [[thread_index_in_threadgroup]])
{
    threadgroup float rir_shared_off5_v7[256];
    const uint row_v0 = group_id.x;
    if (row_v0 >= pc.n_row) {
        return;
    }
    const uint plane_v1 = group_id.y;
    if (plane_v1 >= pc.n_plane) {
        return;
    }
    const uint batch_v2 = group_id.z;
    if (batch_v2 >= pc.n_batch) {
        return;
    }
    const uint lane_v3 = threadgroup_lane_id;
    float part5_v4 = 0.0f;
    const uint base_v12 = row_v0 * pc.x_nb1 + plane_v1 * pc.x_nb2 + batch_v2 * pc.x_nb3;
    const uint chunk_col_v5 = (pc.n_col + 256u - 1u) / 256u;
    const uint beg_col_v5 = min(lane_v3 * chunk_col_v5, pc.n_col);
    const uint end_col_v5 = min((lane_v3 + 1u) * chunk_col_v5, pc.n_col);
    for (uint col_v5 = beg_col_v5; col_v5 < end_col_v5; ++col_v5) {
        const float t_v6 = *(device const float *)(x + (col_v5 * pc.x_nb0 + base_v12));
        part5_v4 += t_v6;
    }
    rir_shared_off5_v7[threadgroup_lane_id] = part5_v4;
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint up_off5_v7 = 1u; up_off5_v7 < 256u; up_off5_v7 <<= 1u) {
        const uint up_idx_off5_v7 = (threadgroup_lane_id + 1u) * 2u * up_off5_v7 - 1u;
        if (up_idx_off5_v7 < 256u) {
            rir_shared_off5_v7[up_idx_off5_v7] = rir_shared_off5_v7[up_idx_off5_v7 - up_off5_v7] + rir_shared_off5_v7[up_idx_off5_v7];
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
    }
    if (threadgroup_lane_id == 0u) {
        rir_shared_off5_v7[255u] = 0.0f;
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint down_off5_v7 = 128u; down_off5_v7 > 0u; down_off5_v7 >>= 1u) {
        const uint down_idx_off5_v7 = (threadgroup_lane_id + 1u) * 2u * down_off5_v7 - 1u;
        if (down_idx_off5_v7 < 256u) {
            const float swap_off5_v7 = rir_shared_off5_v7[down_idx_off5_v7 - down_off5_v7];
            rir_shared_off5_v7[down_idx_off5_v7 - down_off5_v7] = rir_shared_off5_v7[down_idx_off5_v7];
            rir_shared_off5_v7[down_idx_off5_v7] = rir_shared_off5_v7[down_idx_off5_v7] + swap_off5_v7;
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
    }
    const float off5_v7 = rir_shared_off5_v7[threadgroup_lane_id];
    float scan5_v9 = 0.0f;
    scan5_v9 += off5_v7;
    const uint base_v13 = row_v0 * pc.x_nb1 + plane_v1 * pc.x_nb2 + batch_v2 * pc.x_nb3;
    const uint base_v14 = row_v0 * pc.y_nb1 + plane_v1 * pc.y_nb2 + batch_v2 * pc.y_nb3;
    const uint chunk_col_v8 = (pc.n_col + 256u - 1u) / 256u;
    const uint beg_col_v8 = min(lane_v3 * chunk_col_v8, pc.n_col);
    const uint end_col_v8 = min((lane_v3 + 1u) * chunk_col_v8, pc.n_col);
    for (uint col_v8 = beg_col_v8; col_v8 < end_col_v8; ++col_v8) {
        const float t_v10 = *(device const float *)(x + (col_v8 * pc.x_nb0 + base_v13));
        scan5_v9 += t_v10;
        const float s5_v11 = scan5_v9;
        *(device float *)(y + (col_v8 * pc.y_nb0 + base_v14)) = s5_v11;
    }
}

// ---- out_prod ----
struct rir_out_prod_params {
    uint n_i;
    uint n_j;
    uint n_plane;
    uint n_batch;
    uint n_k;
    uint a_nb0;
    uint a_nb1;
    uint a_nb2;
    uint a_nb3;
    uint b_nb0;
    uint b_nb1;
    uint b_nb2;
    uint b_nb3;
    uint dst_nb0;
    uint dst_nb1;
    uint dst_nb2;
    uint dst_nb3;
};

kernel void rir_out_prod(
    device const uchar* a [[buffer(0)]],
    device const uchar* b [[buffer(1)]],
    device uchar* dst [[buffer(2)]],
    constant rir_out_prod_params& pc [[buffer(3)]],
    uint3 group_id [[threadgroup_position_in_grid]],
    uint3 global_id [[thread_position_in_grid]],
    uint threadgroup_lane_id [[thread_index_in_threadgroup]])
{
    threadgroup float rir_shared_tile_a_v12[1024];
    threadgroup float rir_shared_tile_b_v17[256];
    const uint i_v0 = global_id.x * 4u;
    const uint j_v1 = global_id.y;
    const uint plane_v2 = global_id.z;
    if (plane_v2 >= pc.n_plane) {
        return;
    }
    const uint blk_v4 = i_v0 / 64u;
    const uint org_v5 = blk_v4 * 64u;
    const uint loc_v6 = i_v0 % 64u;
    const uint blk_v7 = j_v1 / 16u;
    const uint org_v8 = blk_v7 * 16u;
    const uint loc_v9 = j_v1 % 16u;
    const uint base_v32 = i_v0 * pc.dst_nb0 + j_v1 * pc.dst_nb1 + plane_v2 * pc.dst_nb2;
    for (uint batch_v3 = 0u; batch_v3 < pc.n_batch; ++batch_v3) {
        float4 acc8_v10 = float4(0.0f);
        const uint base_v30 = plane_v2 * pc.a_nb2 + batch_v3 * pc.a_nb3;
        const uint base_v31 = plane_v2 * pc.b_nb2 + batch_v3 * pc.b_nb3;
        for (uint k0_v11 = 0u; k0_v11 < pc.n_k; k0_v11 += 16u) {
            threadgroup_barrier(mem_flags::mem_threadgroup);
            for (uint l_tile_a_v12 = threadgroup_lane_id; l_tile_a_v12 < 1024u; l_tile_a_v12 += 256u) {
                const uint a_r_v13 = l_tile_a_v12 % 64u;
                const uint a_d_v14 = l_tile_a_v12 / 64u;
                const uint a_m_v15 = org_v5 + a_r_v13;
                const uint a_k_v16 = k0_v11 + a_d_v14;
                rir_shared_tile_a_v12[l_tile_a_v12] = (a_m_v15 < pc.n_i && a_k_v16 < pc.n_k) ? *(device const float *)(a + (a_m_v15 * pc.a_nb0 + a_k_v16 * pc.a_nb1 + base_v30)) : 0.0f;
            }
            for (uint l_tile_b_v17 = threadgroup_lane_id; l_tile_b_v17 < 256u; l_tile_b_v17 += 256u) {
                const uint b_r_v18 = l_tile_b_v17 % 16u;
                const uint b_d_v19 = l_tile_b_v17 / 16u;
                const uint b_m_v20 = org_v8 + b_r_v18;
                const uint b_k_v21 = k0_v11 + b_d_v19;
                rir_shared_tile_b_v17[l_tile_b_v17] = (b_m_v20 < pc.n_j && b_k_v21 < pc.n_k) ? *(device const float *)(b + (b_m_v20 * pc.b_nb0 + b_k_v21 * pc.b_nb1 + base_v31)) : 0.0f;
            }
            threadgroup_barrier(mem_flags::mem_threadgroup);
            for (uint kk_v22 = 0u; kk_v22 < 16u; ++kk_v22) {
                const uint row_v23 = kk_v22 * 64u;
                const uint at_v24 = row_v23 + loc_v6;
                const float4 t_v25 = float4(rir_shared_tile_a_v12[at_v24], rir_shared_tile_a_v12[at_v24 + 1u], rir_shared_tile_a_v12[at_v24 + 2u], rir_shared_tile_a_v12[at_v24 + 3u]);
                const uint row_v26 = kk_v22 * 16u;
                const uint at_v27 = row_v26 + loc_v9;
                const float t_v28 = rir_shared_tile_b_v17[at_v27];
                const float4 t_v29 = t_v25 * t_v28;
                acc8_v10 += t_v29;
            }
        }
        if (j_v1 < pc.n_j) {
            if (i_v0 + 4u <= pc.n_i) {
                *(device packed_float4 *)(dst + (batch_v3 * pc.dst_nb3 + base_v32)) = packed_float4(acc8_v10);
            } else {
                for (uint c = 0u; c + i_v0 < pc.n_i; ++c) {
                    *(device float *)(dst + (batch_v3 * pc.dst_nb3 + base_v32) + c * pc.dst_nb0) = acc8_v10[c];
                }
            }
        }
    }
}

// ---- rms_norm_back ----
struct rir_rms_norm_back_params {
    float eps;
    uint n_row;
    uint n_plane;
    uint n_batch;
    uint n_col;
    uint dz_nb0;
    uint dz_nb1;
    uint dz_nb2;
    uint dz_nb3;
    uint x_nb0;
    uint x_nb1;
    uint x_nb2;
    uint x_nb3;
    uint dx_nb0;
    uint dx_nb1;
    uint dx_nb2;
    uint dx_nb3;
};

kernel void rir_rms_norm_back(
    device const uchar* dz [[buffer(0)]],
    device const uchar* x [[buffer(1)]],
    device uchar* dx [[buffer(2)]],
    constant rir_rms_norm_back_params& pc [[buffer(3)]],
    uint3 group_id [[threadgroup_position_in_grid]],
    uint3 global_id [[thread_position_in_grid]],
    uint simd_lane_id [[thread_index_in_simdgroup]])
{
    const uint row_v0 = group_id.x;
    if (row_v0 >= pc.n_row) {
        return;
    }
    const uint plane_v1 = group_id.y;
    if (plane_v1 >= pc.n_plane) {
        return;
    }
    const uint batch_v2 = group_id.z;
    if (batch_v2 >= pc.n_batch) {
        return;
    }
    const uint lane_v3 = simd_lane_id;
    float acc9_v4 = 0.0f;
    float acc10_v5 = 0.0f;
    const uint base_v31 = row_v0 * pc.x_nb1 + plane_v1 * pc.x_nb2 + batch_v2 * pc.x_nb3;
    const uint base_v32 = row_v0 * pc.dz_nb1 + plane_v1 * pc.dz_nb2 + batch_v2 * pc.dz_nb3;
    for (uint col_v6 = lane_v3; col_v6 < pc.n_col; col_v6 += 32u) {
        const float t_v7 = *(device const float *)(x + (col_v6 * pc.x_nb0 + base_v31));
        const float t_v8 = t_v7 * t_v7;
        acc9_v4 += t_v8;
        const float t_v9 = *(device const float *)(dz + (col_v6 * pc.dz_nb0 + base_v32));
        const float t_v10 = t_v7 * t_v9;
        acc10_v5 += t_v10;
    }
    const float red9_v11 = simd_sum(acc9_v4);
    const float red10_v12 = simd_sum(acc10_v5);
    const uint base_v33 = row_v0 * pc.dz_nb1 + plane_v1 * pc.dz_nb2 + batch_v2 * pc.dz_nb3;
    const uint base_v34 = row_v0 * pc.x_nb1 + plane_v1 * pc.x_nb2 + batch_v2 * pc.x_nb3;
    const float c_v16 = 0.0;
    const float t_v17 = c_v16 - red10_v12;
    const float p_v18 = pc.eps;
    const float n_v19 = float(pc.n_col);
    const float t_v20 = p_v18 * n_v19;
    const float t_v21 = red9_v11 + t_v20;
    const float t_v22 = t_v17 / t_v21;
    const float c_v25 = 1.0;
    const float t_v26 = red9_v11 / n_v19;
    const float t_v27 = t_v26 + p_v18;
    const float t_v28 = sqrt(t_v27);
    const float t_v29 = c_v25 / t_v28;
    const uint base_v35 = row_v0 * pc.dx_nb1 + plane_v1 * pc.dx_nb2 + batch_v2 * pc.dx_nb3;
    for (uint col_v13 = lane_v3; col_v13 < pc.n_col; col_v13 += 32u) {
        const float t_v14 = *(device const float *)(dz + (col_v13 * pc.dz_nb0 + base_v33));
        const float t_v15 = *(device const float *)(x + (col_v13 * pc.x_nb0 + base_v34));
        const float t_v23 = t_v15 * t_v22;
        const float t_v24 = t_v14 + t_v23;
        const float t_v30 = t_v24 * t_v29;
        *(device float *)(dx + (col_v13 * pc.dx_nb0 + base_v35)) = t_v30;
    }
}

// ---- rms_norm_back_shared_reduce ----
struct rir_rms_norm_back_shared_reduce_params {
    float eps;
    uint n_row;
    uint n_plane;
    uint n_batch;
    uint n_col;
    uint dz_nb0;
    uint dz_nb1;
    uint dz_nb2;
    uint dz_nb3;
    uint x_nb0;
    uint x_nb1;
    uint x_nb2;
    uint x_nb3;
    uint dx_nb0;
    uint dx_nb1;
    uint dx_nb2;
    uint dx_nb3;
};

kernel void rir_rms_norm_back_shared_reduce(
    device const uchar* dz [[buffer(0)]],
    device const uchar* x [[buffer(1)]],
    device uchar* dx [[buffer(2)]],
    constant rir_rms_norm_back_shared_reduce_params& pc [[buffer(3)]],
    uint3 group_id [[threadgroup_position_in_grid]],
    uint3 global_id [[thread_position_in_grid]],
    uint threadgroup_lane_id [[thread_index_in_threadgroup]])
{
    threadgroup float rir_shared_red9_v11[256];
    threadgroup float rir_shared_red10_v12[256];
    const uint row_v0 = group_id.x;
    if (row_v0 >= pc.n_row) {
        return;
    }
    const uint plane_v1 = group_id.y;
    if (plane_v1 >= pc.n_plane) {
        return;
    }
    const uint batch_v2 = group_id.z;
    if (batch_v2 >= pc.n_batch) {
        return;
    }
    const uint lane_v3 = threadgroup_lane_id;
    float acc9_v4 = 0.0f;
    float acc10_v5 = 0.0f;
    const uint base_v31 = row_v0 * pc.x_nb1 + plane_v1 * pc.x_nb2 + batch_v2 * pc.x_nb3;
    const uint base_v32 = row_v0 * pc.dz_nb1 + plane_v1 * pc.dz_nb2 + batch_v2 * pc.dz_nb3;
    for (uint col_v6 = lane_v3; col_v6 < pc.n_col; col_v6 += 256u) {
        const float t_v7 = *(device const float *)(x + (col_v6 * pc.x_nb0 + base_v31));
        const float t_v8 = t_v7 * t_v7;
        acc9_v4 += t_v8;
        const float t_v9 = *(device const float *)(dz + (col_v6 * pc.dz_nb0 + base_v32));
        const float t_v10 = t_v7 * t_v9;
        acc10_v5 += t_v10;
    }
    rir_shared_red9_v11[threadgroup_lane_id] = acc9_v4;
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint stride_red9_v11 = 128u; stride_red9_v11 > 0u; stride_red9_v11 >>= 1u) {
        if (threadgroup_lane_id < stride_red9_v11) {
            rir_shared_red9_v11[threadgroup_lane_id] = rir_shared_red9_v11[threadgroup_lane_id] + rir_shared_red9_v11[threadgroup_lane_id + stride_red9_v11];
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
    }
    const float red9_v11 = rir_shared_red9_v11[0];
    rir_shared_red10_v12[threadgroup_lane_id] = acc10_v5;
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint stride_red10_v12 = 128u; stride_red10_v12 > 0u; stride_red10_v12 >>= 1u) {
        if (threadgroup_lane_id < stride_red10_v12) {
            rir_shared_red10_v12[threadgroup_lane_id] = rir_shared_red10_v12[threadgroup_lane_id] + rir_shared_red10_v12[threadgroup_lane_id + stride_red10_v12];
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
    }
    const float red10_v12 = rir_shared_red10_v12[0];
    const uint base_v33 = row_v0 * pc.dz_nb1 + plane_v1 * pc.dz_nb2 + batch_v2 * pc.dz_nb3;
    const uint base_v34 = row_v0 * pc.x_nb1 + plane_v1 * pc.x_nb2 + batch_v2 * pc.x_nb3;
    const float c_v16 = 0.0;
    const float t_v17 = c_v16 - red10_v12;
    const float p_v18 = pc.eps;
    const float n_v19 = float(pc.n_col);
    const float t_v20 = p_v18 * n_v19;
    const float t_v21 = red9_v11 + t_v20;
    const float t_v22 = t_v17 / t_v21;
    const float c_v25 = 1.0;
    const float t_v26 = red9_v11 / n_v19;
    const float t_v27 = t_v26 + p_v18;
    const float t_v28 = sqrt(t_v27);
    const float t_v29 = c_v25 / t_v28;
    const uint base_v35 = row_v0 * pc.dx_nb1 + plane_v1 * pc.dx_nb2 + batch_v2 * pc.dx_nb3;
    for (uint col_v13 = lane_v3; col_v13 < pc.n_col; col_v13 += 256u) {
        const float t_v14 = *(device const float *)(dz + (col_v13 * pc.dz_nb0 + base_v33));
        const float t_v15 = *(device const float *)(x + (col_v13 * pc.x_nb0 + base_v34));
        const float t_v23 = t_v15 * t_v22;
        const float t_v24 = t_v14 + t_v23;
        const float t_v30 = t_v24 * t_v29;
        *(device float *)(dx + (col_v13 * pc.dx_nb0 + base_v35)) = t_v30;
    }
}

// ---- add ----
struct rir_add_params {
    uint n_col;
    uint n_row;
    uint n_plane;
    uint n_batch;
    uint a_nb0;
    uint a_nb1;
    uint a_nb2;
    uint a_nb3;
    uint b_nb0;
    uint b_nb1;
    uint b_nb2;
    uint b_nb3;
    uint dst_nb0;
    uint dst_nb1;
    uint dst_nb2;
    uint dst_nb3;
};

kernel void rir_add(
    device const uchar* a [[buffer(0)]],
    device const uchar* b [[buffer(1)]],
    device uchar* dst [[buffer(2)]],
    constant rir_add_params& pc [[buffer(3)]],
    uint3 group_id [[threadgroup_position_in_grid]],
    uint3 global_id [[thread_position_in_grid]],
    uint simd_lane_id [[thread_index_in_simdgroup]])
{
    const uint col_v0 = global_id.x;
    if (col_v0 >= pc.n_col) {
        return;
    }
    const uint row_v1 = global_id.y;
    if (row_v1 >= pc.n_row) {
        return;
    }
    const uint plane_v2 = global_id.z;
    if (plane_v2 >= pc.n_plane) {
        return;
    }
    const uint base_v7 = col_v0 * pc.a_nb0 + row_v1 * pc.a_nb1 + plane_v2 * pc.a_nb2;
    const uint base_v8 = col_v0 * pc.b_nb0 + row_v1 * pc.b_nb1 + plane_v2 * pc.b_nb2;
    const uint base_v9 = col_v0 * pc.dst_nb0 + row_v1 * pc.dst_nb1 + plane_v2 * pc.dst_nb2;
    for (uint batch_v3 = 0u; batch_v3 < pc.n_batch; ++batch_v3) {
        const float t_v4 = *(device const float *)(a + (batch_v3 * pc.a_nb3 + base_v7));
        const float t_v5 = *(device const float *)(b + (batch_v3 * pc.b_nb3 + base_v8));
        const float t_v6 = t_v4 + t_v5;
        *(device float *)(dst + (batch_v3 * pc.dst_nb3 + base_v9)) = t_v6;
    }
}

// ---- add_vec4 ----
struct rir_add_vec4_params {
    uint n_col;
    uint n_row;
    uint n_plane;
    uint n_batch;
    uint a_nb0;
    uint a_nb1;
    uint a_nb2;
    uint a_nb3;
    uint b_nb0;
    uint b_nb1;
    uint b_nb2;
    uint b_nb3;
    uint dst_nb0;
    uint dst_nb1;
    uint dst_nb2;
    uint dst_nb3;
};

kernel void rir_add_vec4(
    device const uchar* a [[buffer(0)]],
    device const uchar* b [[buffer(1)]],
    device uchar* dst [[buffer(2)]],
    constant rir_add_vec4_params& pc [[buffer(3)]],
    uint3 group_id [[threadgroup_position_in_grid]],
    uint3 global_id [[thread_position_in_grid]],
    uint simd_lane_id [[thread_index_in_simdgroup]])
{
    const uint col_v0 = global_id.x * 4u;
    if (col_v0 >= pc.n_col) {
        return;
    }
    const uint row_v1 = global_id.y;
    if (row_v1 >= pc.n_row) {
        return;
    }
    const uint plane_v2 = global_id.z;
    if (plane_v2 >= pc.n_plane) {
        return;
    }
    const uint base_v14 = col_v0 * pc.a_nb0 + row_v1 * pc.a_nb1 + plane_v2 * pc.a_nb2;
    const uint base_v15 = col_v0 * pc.b_nb0 + row_v1 * pc.b_nb1 + plane_v2 * pc.b_nb2;
    const uint base_v16 = col_v0 * pc.dst_nb0 + row_v1 * pc.dst_nb1 + plane_v2 * pc.dst_nb2;
    for (uint batch_v3 = 0u; batch_v3 < pc.n_batch; ++batch_v3) {
        const uint base_v11 = row_v1 * pc.a_nb1 + plane_v2 * pc.a_nb2 + batch_v3 * pc.a_nb3;
        const uint base_v12 = row_v1 * pc.b_nb1 + plane_v2 * pc.b_nb2 + batch_v3 * pc.b_nb3;
        const uint base_v13 = row_v1 * pc.dst_nb1 + plane_v2 * pc.dst_nb2 + batch_v3 * pc.dst_nb3;
        if (col_v0 + 4u <= pc.n_col) {
            const float4 t_v4 = *(device const packed_float4 *)(a + (batch_v3 * pc.a_nb3 + base_v14));
            const float4 t_v5 = *(device const packed_float4 *)(b + (batch_v3 * pc.b_nb3 + base_v15));
            const float4 t_v6 = t_v4 + t_v5;
            *(device packed_float4 *)(dst + (batch_v3 * pc.dst_nb3 + base_v16)) = packed_float4(t_v6);
        } else {
            for (uint col_tail_v7 = col_v0; col_tail_v7 < pc.n_col; ++col_tail_v7) {
                const float t_v8 = *(device const float *)(a + (col_tail_v7 * pc.a_nb0 + base_v11));
                const float t_v9 = *(device const float *)(b + (col_tail_v7 * pc.b_nb0 + base_v12));
                const float t_v10 = t_v8 + t_v9;
                *(device float *)(dst + (col_tail_v7 * pc.dst_nb0 + base_v13)) = t_v10;
            }
        }
    }
}

// ---- mul ----
struct rir_mul_params {
    uint n_col;
    uint n_row;
    uint n_plane;
    uint n_batch;
    uint a_nb0;
    uint a_nb1;
    uint a_nb2;
    uint a_nb3;
    uint b_nb0;
    uint b_nb1;
    uint b_nb2;
    uint b_nb3;
    uint dst_nb0;
    uint dst_nb1;
    uint dst_nb2;
    uint dst_nb3;
};

kernel void rir_mul(
    device const uchar* a [[buffer(0)]],
    device const uchar* b [[buffer(1)]],
    device uchar* dst [[buffer(2)]],
    constant rir_mul_params& pc [[buffer(3)]],
    uint3 group_id [[threadgroup_position_in_grid]],
    uint3 global_id [[thread_position_in_grid]],
    uint simd_lane_id [[thread_index_in_simdgroup]])
{
    const uint col_v0 = global_id.x;
    if (col_v0 >= pc.n_col) {
        return;
    }
    const uint row_v1 = global_id.y;
    if (row_v1 >= pc.n_row) {
        return;
    }
    const uint plane_v2 = global_id.z;
    if (plane_v2 >= pc.n_plane) {
        return;
    }
    const uint base_v7 = col_v0 * pc.a_nb0 + row_v1 * pc.a_nb1 + plane_v2 * pc.a_nb2;
    const uint base_v8 = col_v0 * pc.b_nb0 + row_v1 * pc.b_nb1 + plane_v2 * pc.b_nb2;
    const uint base_v9 = col_v0 * pc.dst_nb0 + row_v1 * pc.dst_nb1 + plane_v2 * pc.dst_nb2;
    for (uint batch_v3 = 0u; batch_v3 < pc.n_batch; ++batch_v3) {
        const float t_v4 = *(device const float *)(a + (batch_v3 * pc.a_nb3 + base_v7));
        const float t_v5 = *(device const float *)(b + (batch_v3 * pc.b_nb3 + base_v8));
        const float t_v6 = t_v4 * t_v5;
        *(device float *)(dst + (batch_v3 * pc.dst_nb3 + base_v9)) = t_v6;
    }
}

// ---- mul_vec4 ----
struct rir_mul_vec4_params {
    uint n_col;
    uint n_row;
    uint n_plane;
    uint n_batch;
    uint a_nb0;
    uint a_nb1;
    uint a_nb2;
    uint a_nb3;
    uint b_nb0;
    uint b_nb1;
    uint b_nb2;
    uint b_nb3;
    uint dst_nb0;
    uint dst_nb1;
    uint dst_nb2;
    uint dst_nb3;
};

kernel void rir_mul_vec4(
    device const uchar* a [[buffer(0)]],
    device const uchar* b [[buffer(1)]],
    device uchar* dst [[buffer(2)]],
    constant rir_mul_vec4_params& pc [[buffer(3)]],
    uint3 group_id [[threadgroup_position_in_grid]],
    uint3 global_id [[thread_position_in_grid]],
    uint simd_lane_id [[thread_index_in_simdgroup]])
{
    const uint col_v0 = global_id.x * 4u;
    if (col_v0 >= pc.n_col) {
        return;
    }
    const uint row_v1 = global_id.y;
    if (row_v1 >= pc.n_row) {
        return;
    }
    const uint plane_v2 = global_id.z;
    if (plane_v2 >= pc.n_plane) {
        return;
    }
    const uint base_v14 = col_v0 * pc.a_nb0 + row_v1 * pc.a_nb1 + plane_v2 * pc.a_nb2;
    const uint base_v15 = col_v0 * pc.b_nb0 + row_v1 * pc.b_nb1 + plane_v2 * pc.b_nb2;
    const uint base_v16 = col_v0 * pc.dst_nb0 + row_v1 * pc.dst_nb1 + plane_v2 * pc.dst_nb2;
    for (uint batch_v3 = 0u; batch_v3 < pc.n_batch; ++batch_v3) {
        const uint base_v11 = row_v1 * pc.a_nb1 + plane_v2 * pc.a_nb2 + batch_v3 * pc.a_nb3;
        const uint base_v12 = row_v1 * pc.b_nb1 + plane_v2 * pc.b_nb2 + batch_v3 * pc.b_nb3;
        const uint base_v13 = row_v1 * pc.dst_nb1 + plane_v2 * pc.dst_nb2 + batch_v3 * pc.dst_nb3;
        if (col_v0 + 4u <= pc.n_col) {
            const float4 t_v4 = *(device const packed_float4 *)(a + (batch_v3 * pc.a_nb3 + base_v14));
            const float4 t_v5 = *(device const packed_float4 *)(b + (batch_v3 * pc.b_nb3 + base_v15));
            const float4 t_v6 = t_v4 * t_v5;
            *(device packed_float4 *)(dst + (batch_v3 * pc.dst_nb3 + base_v16)) = packed_float4(t_v6);
        } else {
            for (uint col_tail_v7 = col_v0; col_tail_v7 < pc.n_col; ++col_tail_v7) {
                const float t_v8 = *(device const float *)(a + (col_tail_v7 * pc.a_nb0 + base_v11));
                const float t_v9 = *(device const float *)(b + (col_tail_v7 * pc.b_nb0 + base_v12));
                const float t_v10 = t_v8 * t_v9;
                *(device float *)(dst + (col_tail_v7 * pc.dst_nb0 + base_v13)) = t_v10;
            }
        }
    }
}

// ---- scale ----
struct rir_scale_params {
    float scale;
    float bias;
    uint n_col;
    uint n_row;
    uint n_plane;
    uint n_batch;
    uint a_nb0;
    uint a_nb1;
    uint a_nb2;
    uint a_nb3;
    uint dst_nb0;
    uint dst_nb1;
    uint dst_nb2;
    uint dst_nb3;
};

kernel void rir_scale(
    device const uchar* a [[buffer(0)]],
    device uchar* dst [[buffer(1)]],
    constant rir_scale_params& pc [[buffer(2)]],
    uint3 group_id [[threadgroup_position_in_grid]],
    uint3 global_id [[thread_position_in_grid]],
    uint simd_lane_id [[thread_index_in_simdgroup]])
{
    const uint col_v0 = global_id.x * 4u;
    if (col_v0 >= pc.n_col) {
        return;
    }
    const uint row_v1 = global_id.y;
    if (row_v1 >= pc.n_row) {
        return;
    }
    const uint plane_v2 = global_id.z;
    if (plane_v2 >= pc.n_plane) {
        return;
    }
    const float p_v11 = pc.scale;
    const float p_v13 = pc.bias;
    const uint base_v17 = col_v0 * pc.a_nb0 + row_v1 * pc.a_nb1 + plane_v2 * pc.a_nb2;
    const float p_v5 = pc.scale;
    const float p_v7 = pc.bias;
    const uint base_v18 = col_v0 * pc.dst_nb0 + row_v1 * pc.dst_nb1 + plane_v2 * pc.dst_nb2;
    for (uint batch_v3 = 0u; batch_v3 < pc.n_batch; ++batch_v3) {
        const uint base_v15 = row_v1 * pc.a_nb1 + plane_v2 * pc.a_nb2 + batch_v3 * pc.a_nb3;
        const uint base_v16 = row_v1 * pc.dst_nb1 + plane_v2 * pc.dst_nb2 + batch_v3 * pc.dst_nb3;
        if (col_v0 + 4u <= pc.n_col) {
            const float4 t_v4 = *(device const packed_float4 *)(a + (batch_v3 * pc.a_nb3 + base_v17));
            const float4 t_v6 = t_v4 * p_v5;
            const float4 t_v8 = t_v6 + p_v7;
            *(device packed_float4 *)(dst + (batch_v3 * pc.dst_nb3 + base_v18)) = packed_float4(t_v8);
        } else {
            for (uint col_tail_v9 = col_v0; col_tail_v9 < pc.n_col; ++col_tail_v9) {
                const float t_v10 = *(device const float *)(a + (col_tail_v9 * pc.a_nb0 + base_v15));
                const float t_v12 = t_v10 * p_v11;
                const float t_v14 = t_v12 + p_v13;
                *(device float *)(dst + (col_tail_v9 * pc.dst_nb0 + base_v16)) = t_v14;
            }
        }
    }
}
