// Generated by rir-gen — DO NOT EDIT MANUALLY.
// Every production RIR launch stub for CUDA, as an X-macro
// (docs/CUDA_v1.md §C2). `rir-cuda-launch.cu` expands this list twice:
// once to declare the stubs, once to build the artifact → pointer table.
//
// The name is the artifact name. The stub it declares is
// `rir_launch_<name>`, defined by `rir/rir_<name>.cu`, which the
// backend's `file(GLOB "rir/*.cu")` compiles — so adding a variant
// edits no vendored file.
#pragma once

#define RIR_CUDA_LAUNCHERS(X) \
    /* no RIR kernel in this build */
